---
- name: Configure VLANs
  hosts: arista
  gather_facts: false

  tasks:
    - name: Get the vlan details pre config
      arista.eos.eos_vlans:
        state: gathered
      register: vlan_config

    - name: Vlan details before configurations
      ansible.builtin.debug:
        msg: "{{ vlan_config.gathered }}"

    - name: Configure Vlans
      arista.eos.eos_vlans:
        state: merged
        config:
          - name: desktops
            vlan_id: 20
          - name: servers
            vlan_id: 30
          - name: printers
            vlan_id: 40
          - name: DMZ
            vlan_id: 50

    - name: Get the vlan details post config
      arista.eos.eos_vlans:
        state: gathered
      register: vlan_config
      
    - name: Vlan details after configurations
      ansible.builtin.debug:
        msg: "{{ vlan_config.gathered }}"

   # - name: Fail the playbook
   #   fail:
    #    msg: Testing the flow.
