---
- name: SNMP ro/rw string configuration
  hosts: cisco
  gather_facts: false

  tasks:
    - name: Get the snmp details
      cisco.ios.command:
        commands:
          - sh run | sec snmp
      register: snmp_data

    - name: print snmp data pre config
      ansible.builtin.debug:
        msg: "{{ snmp_data }}"

    - name: Get the acl config details
      cisco.ios.command:
        commands:
          - sh run | sec access-list
      register: acl_data

    - name: print the acl data pre config
      ansible.builtin.debug:
        msg: "{{ acl_data }}"
        
    - name: Ensure that the desired snmp strings are present
      cisco.ios.ios_config:
        commands:
          - snmp-server community ansible-public RO
          - snmp-server community ansible-private RW

    - name: Get the snmp details
      cisco.ios.command:
        commands:
          - sh run | sec snmp
      register: snmp_data
      
    - name: print snmp data post config
      ansible.builtin.debug:
        msg: "{{ snmp_data }}"
      
    - name: Get the acl config details
      cisco.ios.command:
        commands:
          - sh run | sec access-list
      register: acl_data

    - name: print the acl data pre config
      ansible.builtin.debug:
        msg: "{{ acl_data }}"
      
